### ISSUE TITLE
Support of r2dbc

### ISSUE THREAD

**Issue by energy2522** [joutvhu/spring-dynamic-jpa#18]
Hi,

I see this powerful library but unfortunately when I try to use it with spring r2dbc it fails. Are you planning to add support for spring data r2dbc?

**Comment by joutvhu** [comment]
I will add support for spring data r2dbc.

**Comment by joutvhu** [comment]
I have created a new library [spring-dynamic-r2dbc](https://github.com/joutvhu/spring-dynamic-r2dbc) to support spring-data-r2dbc package.
