### ISSUE TITLE
dependency to hibernate-core

### ISSUE THREAD

**Issue by cbrethes** [joutvhu/spring-dynamic-jpa#24]
Hi, 

Just great job for this project ! 

I just want to let you know you have a runtime dependancy to hibernate-core.jar just because class DynamicJpaParameterAccessor is using org.hibernate.jpa.TypedParameterValue

I was using your lib using hibenate exclusion and everything was working well until version 2.3.3
`            <dependency>
                <artifactId>spring-dynamic-jpa</artifactId>
                <groupId>com.github.joutvhu</groupId>
                <version>${spring-dynamic-jpa.version}</version>
                
               <exclusions>
                 <exclusion>
            		<groupId>org.hibernate</groupId>
            		<artifactId>hibernate-core</artifactId>
            	</exclusion>
	   </exclusions>
            </dependency>`

I think this could be avoided using some reflection code instead.

Best regards, 

Christophe

Used version : 2.7.6

**Comment by joutvhu** [comment]
I fixed it in x.x.7 versions.
However you need to wait a few hours for it to be ready on the maven repository.

**Comment by joutvhu** [comment]
The x.x.7 versions are available on the maven repository, you can switch to using 2.7.7
